name: Publish Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:

jobs:
  publish:
    uses: chronolite-technologies/helm-workflows/.github/workflows/publish-registry.yml@main